import {notFound} from 'next/navigation';
import {Hero,FeatureGrid,DarkCTA,StandardPage} from '../../components/blocks';
const data:any={
 gym:{name:'Gyms',title:'More members. Fewer missed opportunities.',desc:'Raya handles membership questions, trial bookings, lead qualification and follow-ups while your team runs the floor.',accent:'lime',features:[['⚡','Instant membership replies','Answer pricing, timings, trainers and class questions instantly.'],['◫','Trial booking','Move enquiries into trial sessions without back-and-forth.'],['◎','Lead qualification','Ask goals, preferred timings and intent before passing a lead to staff.'],['↻','Follow-ups','Recover leads that asked for pricing but never booked.'],['▣','Reminders','Reduce no-shows with automatic reminders.'],['✦','Owner insights','See leads, trials and bookings from one view.']]},
 clinic:{name:'Clinics',title:'Better patient communication. Smarter appointments.',desc:'Raya answers general business questions, helps patients find the right service and manages appointment workflows.',features:[['⚡','Instant patient replies','Handle routine questions without making patients wait.'],['◫','Appointment booking','Coordinate doctor, service and available slot information.'],['↻','Reminders','Reduce missed appointments with reminders.'],['◎','Rescheduling','Handle common schedule changes before involving staff.'],['✦','Human handoff','Escalate sensitive or non-routine queries to staff.'],['▣','Performance','Track conversations and appointment outcomes.']]},
 salon:{name:'Salons',title:'More bookings. Happier clients. Raya handles it.',desc:'Raya helps salons answer service questions, show pricing, find availability and turn chats into booked slots.',features:[['⚡','Services & pricing','Answer questions about packages, treatments and prices.'],['◫','Slot booking','Turn customer intent into appointments.'],['↻','Reminders','Keep upcoming bookings top of mind.'],['◎','Rescheduling','Handle common schedule changes.'],['✦','Offers','Support promotional campaigns and customer follow-ups.'],['▣','Repeat visits','Re-engage customers after their appointment.']]},
 restaurant:{name:'Restaurants',title:'More orders. Better reservations. Less waiting.',desc:'Raya handles menu questions, reservations, orders and event enquiries so staff can focus on the floor.',features:[['⚡','Menu answers','Respond to common menu, pricing and timing questions.'],['◫','Reservations','Help customers reserve tables and event slots.'],['↻','Order updates','Keep customers informed about the next step.'],['◎','Private events','Capture birthdays, parties and corporate enquiries.'],['✦','Feedback','Collect post-visit feedback and requests.'],['▣','Repeat visits','Bring customers back with targeted follow-ups.']]}
};
export function generateStaticParams(){return Object.keys(data).map(industry=>({industry}))}
export default async function Solution({params}:{params:Promise<{industry:string}>}){const {industry}=await params; const x=data[industry]; if(!x) return notFound(); return <StandardPage hero={<Hero eyebrow={`Solutions — ${x.name}`} title={x.title} desc={x.desc}/>}><FeatureGrid items={x.features.map((f:string[])=>({icon:f[0],title:f[1],desc:f[2]}))}/><section className="section"><div className="container card"><h2 className="h2">A simple customer journey</h2><div className="flow">{['Customer message','Raya replies','Lead qualified','Booking/order','Follow-up'].map((v,i)=><div key={v}><div className="node">{v}</div>{i<4&&<div className="arrow">→</div>}</div>)}</div></div></section><DarkCTA title={`Let Raya handle the ${x.name.toLowerCase()} enquiries.`} desc="Keep the team focused on the customer in front of them while Raya handles the conversations behind the scenes."/></StandardPage>}
